version: '3.8'
services:
  app:
    image: samarafer/docker-atividade:${DOCKER_IMAGE_TAG}
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
