name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build and Push"
    runs-on: ${{ matrix.os }}
    environment: deploy
    outputs:
      docker_tag: ${{ steps.generate_tag.outputs.sha }}

    strategy:
      matrix:
        node-version: [22]
        os: [ubuntu-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

#      - name: Running Tests
#        run: npm run test

      - name: Generate Tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t samarafer/docker-atividade:${{ steps.generate_tag.outputs.sha }} .

      - name: Push Docker Image to DockerHub
        run: docker push samarafer/docker-atividade:${{ steps.generate_tag.outputs.sha }}

  deploy:
    name: Deploy on Digital Ocean
    environment: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install DigitalOcean CLI
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.90.0/doctl-1.90.0-linux-amd64.tar.gz | tar -xz
          sudo mv doctl /usr/local/bin

      - name: Authenticate with DigitalOcean
        run: doctl auth init --access-token ${{ secrets.DIGITALOCEAN_TOKEN }}    
      
      - name: Copy docker-compose file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          source: "./docker-compose.yaml"
          target: "~/"
      
      - name: Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh

          # Add the DigitalOcean Droplet to known_hosts
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

          ssh -i private_key.pem root@${{ secrets.HOST }} "echo SSH Connection Successful"

          # Execute commands on the DigitalOcean Droplet
          doctl compute ssh ${{ secrets.DROPLET_NAME }} \
            --access-token ${{ secrets.DIGITALOCEAN_TOKEN }} \
            --ssh-user root \
            --ssh-key-path ./private_key.pem \
            --ssh-command "
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }};
              docker pull samarafer/docker-atividade:${{ steps.generate_tag.outputs.sha }};
              echo 'DOCKER_IMAGE_TAG=${{ steps.generate_tag.outputs.sha }}' >> .env;
              docker-compose -f docker-compose.yml up -d --build;
            "