name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build and Push"
    runs-on: ${{ matrix.os }}
    environment: deploy

    strategy:
      matrix:
        node-version: [22]
        os: [ubuntu-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

#      - name: Running Tests
#        run: npm run test

      - name: Login into the Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get short commit hash
        id: get_commit_hash
        run: echo "commit_hash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t samarafer/docker-atividade:${{ env.commit_hash }} .

      - name: Push Docker Image to DockerHub
        run: docker push samarafer/docker-atividade:${{ env.commit_hash }}

      - name: Install DigitalOcean CLI
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.90.0/doctl-1.90.0-linux-amd64.tar.gz | tar -xz
          sudo mv doctl /usr/local/bin

      - name: Authenticate with DigitalOcean
        run: doctl auth init --access-token ${{ secrets.DIGITALOCEAN_TOKEN }}    

      - name: Prepare SSH Access
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy docker-compose.yml to server
        run: |
          scp -i private_key.pem docker-compose.yml root@${{ secrets.HOST }}:/root/docker-compose.yml
      
      - name: Deploy
        run: |
          ssh -i private_key.pem root@${{ secrets.HOST }}

          # Ensure the .env file exists
          if [ -f .env ]; then
            # Replace the DOCKER_IMAGE_TAG without removing other data
            sed -i '' 's/^DOCKER_IMAGE_TAG=.*/DOCKER_IMAGE_TAG=${{ env.commit_hash }}/' .env
          else
            echo 'DOCKER_IMAGE_TAG=${{ env.commit_hash }}' >> .env;
          fi

          doctl compute ssh ${{ secrets.DROPLET_NAME }} \
            --access-token ${{ secrets.DIGITALOCEAN_TOKEN }} \
            --ssh-user root \
            --ssh-key-path ./private_key.pem \
            --ssh-command "
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }};
              docker pull samarafer/docker-atividade:${{ env.commit_hash }};
              docker-compose -f docker-compose.yml up -d --build;
            "
